version: "3.7"
services:
    traffik:
        build: .
        container_name: "traffik"
        volumes:
            - .:/home/app
            - /home/app/node_modules
        ports:
            - '8080:8080'
        command:
            "tail -f /dev/null"